### ISSUE TITLE
Remove deepmerge dependecy to avoid optimalization bailouts

### ISSUE THREAD

**Issue by cZalyun** [btroncone/ngrx-store-localstorage#263] opened 2024-02-13 13:12 UTC
Got the following message during the build
<img width="1286" alt="image" src="https://github.com/btroncone/ngrx-store-localstorage/assets/53048598/161f56d5-169e-4da5-9160-19c74381e3ce">

**Comment by BBlackwo** [comment] 2024-02-13 20:56
Duplicate of #229

**Closed by BBlackwo** 2024-02-13 20:56 UTC
